# Visualización

In [67]:
# Import packages

import pandas as pd
import plotly.express as px

Carguen su dataset en assignment_3/datos/. Léanlo con pd.read_csv (si tienen ubigeos, usen dtype=str). Muestren sus dimensiones y las primeras 5 filas.

In [68]:
# Import data

data = pd.read_csv('datos/tabla_final.csv')

data.dtypes

data["ubigeo"] = data["ubigeo"].astype(str)

print("Dimensiones: ", data.shape)

data.head(5)

Dimensiones:  (25, 9)

,ubigeo,departamento,capital,latitud,longitud,lluvia_total_mm,dias_lluvia_fuerte,declaratorias,prorrogas
0,1,Amazonas,Chachapoyas,-6.23169,-77.86903,455.0,0,4,2
1,2,Áncash,Huaraz,-9.52614,-77.52869,1058.3,3,5,5
2,3,Apurímac,Abancay,-13.63426,-72.88380,670.6,2,7,4
3,4,Arequipa,Arequipa,-16.39899,-71.53747,235.3,1,7,6
4,5,Ayacucho,Ayacucho,-13.16380,-74.22345,467.5,1,7,5

En una celda de texto breve, indiquen qué tema o pregunta abordarán y qué columnas usarán.

## Pregunta de investigación 
¿Existe una relación entre el número de decretos de emergencia (declaratorias y prórrogas) y la cantidad de lluvia o el número de días de lluvia fuerte por regiones?

Esta pregunta permitirá mapear la relación entre variables lluvia_total_mm y dias_lluvia_fuerte con el número total de declaratorias de emergencias y prórrogas (sumatoria de declaratorias y prórrogas) para ver cuál muestra una relación más fuerte, siendo la hipótesis que la respuesta será la variable de días pero que la fuerza de la relación cambia por regiones

Por lo tanto, se utilizarán las columnas lluvia_total_mm, dias_lluvia_fuerte y una columna decretos, a crearse con la suma de declaratorias y prorrogas

Creen 3 gráficos interactivos con Plotly Express apoyándose en lo visto en la sesión 6:
- un gráfico de barras (por ejemplo: top de alguna variable por departamento o ciudad);
- un gráfico de dispersión (dos variables continuas, usando hover_name para identificar cada punto);
- un tercer gráfico libre (histograma, boxplot, línea, pastel/treemap, etc.).

### Gráficos de barra

In [69]:
data["decretos"] = data["declaratorias"] + data["prorrogas"]

top_decretos = data.sort_values("decretos", ascending = False)

barra_1 = px.bar(
    top_decretos.head(10),
    x = "departamento",
    y = "decretos",
    title = "Top 10 regiones por número de decretos",
    labels = {
        "departamento" : "Departamento",
        "decretos" : "Número de decretos"
    }
)

barra_1 = barra_1.update_layout(title_x=0.5, title_xanchor="center")

barra_1

In [70]:
top_mm = data.sort_values("lluvia_total_mm", ascending = False)

top_mm.head(5)

,ubigeo,departamento,capital,latitud,longitud,lluvia_total_mm,dias_lluvia_fuerte,declaratorias,prorrogas,decretos
15,16,Loreto,Iquitos,-3.74814,-73.25290,1361.8,19,3,2,5
11,12,Junín,Huancayo,-12.06866,-75.21027,1276.9,11,5,1,6
16,17,Madre de Dios,Puerto Maldonado,-12.58946,-69.19948,1149.5,15,3,0,3
1,2,Áncash,Huaraz,-9.52614,-77.52869,1058.3,3,5,5,10
24,25,Ucayali,Pucallpa,-8.37915,-74.55387,887.4,9,4,0,4

In [71]:
top_dias = data.sort_values("dias_lluvia_fuerte", ascending = False)

top_dias.head(5)

,ubigeo,departamento,capital,latitud,longitud,lluvia_total_mm,dias_lluvia_fuerte,declaratorias,prorrogas,decretos
15,16,Loreto,Iquitos,-3.74814,-73.25290,1361.8,19,3,2,5
16,17,Madre de Dios,Puerto Maldonado,-12.58946,-69.19948,1149.5,15,3,0,3
11,12,Junín,Huancayo,-12.06866,-75.21027,1276.9,11,5,1,6
24,25,Ucayali,Pucallpa,-8.37915,-74.55387,887.4,9,4,0,4
23,24,Tumbes,Tumbes,-3.55592,-80.44258,497.0,3,0,2,2

In [72]:
barra_2 = px.bar(
    top_mm.head(10), 
    x = "departamento", 
    y = "lluvia_total_mm", 
    title = "Top 10 departamentos con mayor lluvia (mm)", 
    labels = {
        "departamento": "Departamento", 
        "lluvia_total_mm": "Lluvia total (mm)"
        }
    )

barra_2 = barra_2.update_coloraxes(showscale=False).update_layout(title_x=0.5, title_xanchor="center")

barra_2.show()

In [73]:
barra_3 = px.bar(
    top_dias.head(10),
    x = "departamento",
    y = "dias_lluvia_fuerte",
    title = "Top 10 departamentos<br>por de días de lluvia fuerte",
    labels = {
        "departamento": "Departamento",
        "dias_lluvia_fuerte": "Días de lluvia fuerte"
    }
)

barra_3.update_layout(title_x=0.5, title_xanchor="center")

barra_3

### Gráficos de dispersión

In [74]:
dispersion_1 = px.scatter(
    data,
    x = "lluvia_total_mm",
    y = "decretos",
    hover_name = "departamento",
    title = "Lluvia en mm<br>vs Número de decretos por región",
    labels = {
        "decretos" : "Número de decretos",
        "lluvia_total_mm" : "Lluvia total en mm"
    }
)

dispersion_1.update_layout(title_x=0.5, title_xanchor="center")

dispersion_1

No parece haber relación entre el número de decretos y la cantidad total de lluvia.

In [59]:
dispersion_2 = px.scatter(
    data,
    x = "dias_lluvia_fuerte",
    y = "decretos",
    hover_name = "departamento",
    title = "Número de días de lluvia fuerte<br>vs número de decretos por región",
    labels = {
        "decretos" : "Número de decretos",
        "dias_lluvia_fuerte" : "Número de días de lluvia fuerte"
    }
)

# Centrar el título
dispersion_2.update_layout(title_x=0.5, title_xanchor="center")

dispersion_2

Puede que exista una relación, aunque debil, entre el número de días de lluvia fuerte y el número de decretos.

### Boxplot

In [63]:
boxplot_1 = px.box(
    data,
    x = "lluvia_total_mm",
    title = "Lluvia total en mm por departamentos",
    labels = {
        "lluvia_total_mm" : "Lluvia en mm"
    }
)

boxplot_1.update_layout(title_x=0.5, title_xanchor="center")

boxplot_1

In [ ]:
boxplot_2 = px.box(
    data,
    x = "dias_lluvia_fuerte",
    hover_name = "departamento",
    title = "Días de lluvia fuerte por departamentos",
    labels = {
        "dias_lluvia_fuerte" : "Número de día de lluvia fuerte"
    }
)

boxplot_2.update_layout(title_x=0.5, title_xanchor="center")

boxplot_2

4 regiones presentan un número de días de lluvia fuerte más alto, atípico en comparación a las regiones.

# HTML del gráfico

In [55]:
dispersion_2.write_html("grafico.html")