# Visualización

In [ ]:
# Import packages

import pandas as pd
import plotly.express as px

Carguen su dataset en assignment_3/datos/. Léanlo con pd.read_csv (si tienen ubigeos, usen dtype=str). Muestren sus dimensiones y las primeras 5 filas.

In [14]:
# Import data

data = pd.read_csv('datos/tabla_final.csv')

data.dtypes

data["ubigeo"] = data["ubigeo"].astype(str)

print("Dimensiones: ", data.shape)

data.head(5)

Dimensiones:  (25, 9)

,ubigeo,departamento,capital,latitud,longitud,lluvia_total_mm,dias_lluvia_fuerte,declaratorias,prorrogas
0,1,Amazonas,Chachapoyas,-6.23169,-77.86903,455.0,0,4,2
1,2,Áncash,Huaraz,-9.52614,-77.52869,1058.3,3,5,5
2,3,Apurímac,Abancay,-13.63426,-72.88380,670.6,2,7,4
3,4,Arequipa,Arequipa,-16.39899,-71.53747,235.3,1,7,6
4,5,Ayacucho,Ayacucho,-13.16380,-74.22345,467.5,1,7,5

En una celda de texto breve, indiquen qué tema o pregunta abordarán y qué columnas usarán.

Propuesta: Mapear la relación entre variables lluvia_total_mm y dias_lluvia_fuerte con el número total de declaratorias de emergencias y prórrogas (sumatoria de declaratorias y prórrogas) para ver cuál muestra una relación más fuerte, siendo la hipótesis que la respuesta será la variable de días pero que la fuerza de la relación cambia por regiones

Creen 3 gráficos interactivos con Plotly Express apoyándose en lo visto en la sesión 6:
- un gráfico de barras (por ejemplo: top de alguna variable por departamento o ciudad);
- un gráfico de dispersión (dos variables continuas, usando hover_name para identificar cada punto);
- un tercer gráfico libre (histograma, boxplot, línea, pastel/treemap, etc.).

In [19]:
top_mm = data.sort_values("lluvia_total_mm", ascending = False)

top_mm.head(5)

,ubigeo,departamento,capital,latitud,longitud,lluvia_total_mm,dias_lluvia_fuerte,declaratorias,prorrogas
15,16,Loreto,Iquitos,-3.74814,-73.25290,1361.8,19,3,2
11,12,Junín,Huancayo,-12.06866,-75.21027,1276.9,11,5,1
16,17,Madre de Dios,Puerto Maldonado,-12.58946,-69.19948,1149.5,15,3,0
1,2,Áncash,Huaraz,-9.52614,-77.52869,1058.3,3,5,5
24,25,Ucayali,Pucallpa,-8.37915,-74.55387,887.4,9,4,0

In [18]:

top_dias = data.sort_values("dias_lluvia_fuerte", ascending = False)

top_dias.head(5)

,ubigeo,departamento,capital,latitud,longitud,lluvia_total_mm,dias_lluvia_fuerte,declaratorias,prorrogas
15,16,Loreto,Iquitos,-3.74814,-73.25290,1361.8,19,3,2
16,17,Madre de Dios,Puerto Maldonado,-12.58946,-69.19948,1149.5,15,3,0
11,12,Junín,Huancayo,-12.06866,-75.21027,1276.9,11,5,1
24,25,Ucayali,Pucallpa,-8.37915,-74.55387,887.4,9,4,0
23,24,Tumbes,Tumbes,-3.55592,-80.44258,497.0,3,0,2